name: Publish Package

on:
  workflow_dispatch:

jobs:
  test-and-publish:
    name: Build Examples and Publish to PlatformIO
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build all examples (esp32doit-devkit-v1)
        run: |
          for f in examples/**/*.ino; do
            echo "Building $f..."
            pio ci --lib="." --board=esp32doit-devkit-v1 "$f" || exit 1
          done

      - name: Publish package
        if: success()
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.AUTHENTICATION_TOKEN }}
        run: pio pkg publish --non-interactive
